### ISSUE TITLE
Running any command ends with spec/_spec.rb

### ISSUE THREAD

**Issue by qortex** [thadeu/vscode-run-rspec-file#10]
Using any of the documented commands in a spec file (for example while in `auth_spec.rb` in my spec folder) spawns `bundle exec rspec --color spec/_spec.rb`

Not usable as a result.

What am I missing?

**Comment by thadeu** [comment]
@qortex I didn't understand your problem, could you explain it better?

**Comment by qortex** [comment]
It's been a while, but from what I remember, whenever I used a keyboard shortcut to spawn the test, it would spawn the given command instead (thus issuing the wrong filename `_spec.rb` instead of `auth_spec.rb`). Thus, it wouldn't work as expected.

I may have missed some kind of config file to setup?

**Comment by thadeu** [comment]
@qortex this problem is solved in the latest version

**Comment by qortex** [comment]
Nice, thanks. I'll close this then.

**Comment by mhluska** [comment]
Im still having this issue in the latest version. The issue happens with cmd+option+l. cmd+option+j is fine

**Comment by thadeu** [comment]
@mhluska is the same scenario?

**Comment by MatheusRich** [comment]
I'm experiencing this with [Packwerk](https://github.com/Shopify/packwerk)

**Comment by thadeu** [comment]
> I'm experiencing this with [Packwerk](https://github.com/Shopify/packwerk)

@MatheusRich Thanks, I'll work in this issue, and soon will create a new version to fix this.

**Comment by thadeu** [comment]
@MatheusRich Do you use docker?

**Comment by MatheusRich** [comment]
Nope. It's a rails app running locally on macos
